package com.bitbucket.learningjava;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'archana' at '5/25/14 9:49 PM' with Gradle 1.12
 *
 * @author archana, @date 5/25/14 9:49 PM
 */
public class TaxCalculator {

    public static final double INC_21450 = 21450.0;
    public static final double RATE_015 = 0.15;
    private static final double RATE_028 = 0.28;
    private static final double RATE_031 = 0.31;
    public static final int INC_51900 = 51900;
    public static final double INC_35800 = 35800.0;
    private static final double INC_86500 = 86500.0;

    public double calculateTax(boolean single, double income) {
        double tax = 0.0;
        if (single) {
            if (income <= INC_21450) {
                tax = income * RATE_015;
            } else if (income <= INC_51900) {
                tax = income * RATE_028;
            } else if (income > INC_51900) {
                tax = income * RATE_031;
            }
        } else
        //if ( not single)
        {
            if (income <= INC_35800) {
                tax = income * RATE_015;
            } else if (income <= INC_86500) {
                tax = income * RATE_028;
            } else if (income > INC_86500) {
                tax = income * RATE_031;
            }


        }


        return tax;
    }


    // public double calculateTax(boolean married, double income) {
    // double tax = 0.0;

    //  return tax;
}






