/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'archana' at '5/25/14 9:49 PM' with Gradle 1.12
 *
 * @author archana, @date 5/25/14 9:49 PM
 */
public class TaxCalculator {
    public double calculateTax( boolean single ,double income ) {



        return  0.0;
    }


}
