import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'archana' at '5/25/14 9:49 PM' with Gradle 1.12
 *
 * @author archana, @date 5/25/14 9:49 PM
 */
public class TaxCalculatorTest {
    @Test public void testSomeLibraryMethod() {
        TaxCalculator classUnderTest = new TaxCalculator();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
