
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;
import java.util.Collection;

import static org.hamcrest.core.Is.*;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'archana' at '5/25/14 9:49 PM' with Gradle 1.12
 *
 * @author archana, @date 5/25/14 9:49 PM
 */
@RunWith(Parameterized.class)
public class TaxCalculatorTest {
    @Parameterized.Parameters( name="single: {0} , income = {1} , tax ={2}")
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][]{

                {true, 20450, 3067.50 }, {true, 21450, 3217.50}, {true, 50000, 14000}, {true, 51900, 14532}, {true, 61000, 18910},
                {false, 20450, 3067.50 }, {false, 35800, 5370.00}, {false, 50000, 14000}, {false, 86500, 24220}, {false, 90000, 27900}
        });
    }

    private boolean single;

    private double income;
    private double tax;

    public TaxCalculatorTest(boolean single, double income, double tax ) {
        this.single = single;
        this.income = income;
        this.tax = tax;
    }

    @Test
    public void test() {

        TaxCalculator classUnderTest = new TaxCalculator();
        double tax = classUnderTest.calculateTax(this.single, this.income);
        assertThat(tax, is(this.tax));
    }

}
